# Generated by Django 4.2.4 on 2023-09-07 00:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar_default.png', upload_to=users.models.avatar_upload_path),
        ),
    ]
