# Generated by Django 4.2.4 on 2023-08-31 22:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=48)),
                ('short_description', models.CharField(max_length=128)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
