# Generated by Django 4.2.4 on 2023-08-31 23:15

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import mods.models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_mod_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=48)),
                ('version', models.SlugField(unique=True)),
                ('changelog', markdownx.models.MarkdownxField()),
                ('file', models.FileField(upload_to=mods.models.version_upload_path)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
    ]
