# Generated by Django 4.2.4 on 2023-08-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_alter_version_changelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version',
            new_name='slug',
        ),
    ]
