# Generated by Django 4.2.4 on 2023-09-01 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mods', '0006_rename_version_version_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
