# Generated by Django 4.2.4 on 2023-09-01 00:34

from django.db import migrations, models
import mods.models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_mod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='logo',
            field=models.ImageField(default='assets/images/mod_default.png', upload_to=mods.models.avatar_upload_path),
        ),
    ]
