# Generated by Django 4.2.4 on 2023-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0012_version_downloads_alter_mod_logo_alter_mod_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='categories',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('cursed', 'Cursed'), ('decoration', 'Decoration')], default='decoration', max_length=30),
            preserve_default=False,
        ),
    ]
