# Generated by Django 4.2.4 on 2023-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0013_mod_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=48)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mod',
            name='categories',
        ),
        migrations.AddField(
            model_name='mod',
            name='categories',
            field=models.ManyToManyField(to='mods.category'),
        ),
    ]
