# Generated by Django 4.2.4 on 2023-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0015_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(),
        ),
    ]
