# Generated by Django 4.2.4 on 2023-09-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0016_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='downloads',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_tracker', models.CharField(max_length=255)),
                ('source_code', models.CharField(max_length=255)),
                ('wiki_page', models.CharField(max_length=255)),
                ('discord_invite', models.CharField(max_length=255)),
                ('donation_links', models.CharField(max_length=255)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mods.mod')),
            ],
        ),
    ]
