# Generated by Django 4.2.4 on 2023-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0017_alter_version_downloads_externallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinks',
            name='discord_invite',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='donation_links',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='issue_tracker',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='source_code',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='wiki_page',
            field=models.URLField(),
        ),
    ]
