# Generated by Django 4.2.4 on 2023-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0018_alter_externallinks_discord_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinks',
            name='discord_invite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='donation_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='issue_tracker',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='source_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='wiki_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
