# Generated by Django 4.2.4 on 2023-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0020_alter_externallinks_discord_invite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
