# Generated by Django 4.2.4 on 2023-09-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0021_releasechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='release_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mods.releasechannel'),
        ),
    ]
