# Generated by Django 4.2.4 on 2023-09-12 16:02

from django.db import migrations, models
import django.db.models.deletion
import mods.models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0022_version_release_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='release_channel',
            field=models.ForeignKey(default=mods.models.ReleaseChannel.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mods.releasechannel'),
        ),
    ]
