# Generated by Django 4.2.4 on 2023-09-12 17:03

from django.db import migrations, models
import django.db.models.deletion
import mods.models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0024_alter_version_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='game_version',
            field=models.ForeignKey(default=mods.models.GameVersion.get_latest, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mods.gameversion'),
        ),
    ]
