# Generated by Django 4.2.4 on 2023-09-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0027_version_loaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='game_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mods.gameversion'),
        ),
    ]
