# Generated by Django 4.2.4 on 2023-11-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='launcher')),
                ('changelog', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
