# Generated by Django 4.2.4 on 2023-11-05 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launcher',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='launcher',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
