# Generated by Django 4.2.4 on 2023-11-05 12:48

from django.db import migrations, models
import launcher.models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_alter_launcher_options_launcher_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='file',
            field=models.FileField(upload_to=launcher.models.launcher_upload_path),
        ),
    ]
